CREATE TRIGGER them_nvphancong ON NHANVIEN INSTEAD OF INSERT AS
BEGIN
	INSERT INTO PHANCONG
	VALUES ((SELECT MANV FROM inserted),1,1,100)
END

INSERT INTO NHANVIEN
VALUES ('Tran', 'Van', 'Toan', '026', '1980-12-12', 'Da Nang', N'Nữ', 16000, '004', 1)
